import type { Metadata } from 'next';
import { Neucha } from 'next/font/google';
import { Background } from '@/components/game/Background/Background';
import '../styles/globals.scss';

const neucha = Neucha({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={neucha.className}
        >
            <body className="min-h-full flex flex-col">
                <Background/>
               
                {children}
            </body>
        </html>
    );
}
