import type { WordCard } from '@/store/game/game.type';

export const testDeck: WordCard[] = [
    { id: '1', word: 'Ant', image: '/cards/ant.svg' },
    { id: '2', word: 'Apple', image: '/cards/apple.svg' },
    { id: '3', word: 'Ball', image: '/cards/ball.svg' },
    { id: '4', word: 'Banana', image: '/cards/banana.svg' },
    { id: '5', word: 'Bear', image: '/cards/bear.svg' },
    { id: '6', word: 'Bee', image: '/cards/bee.svg' },
    { id: '7', word: 'Car', image: '/cards/car.svg' },
    { id: '8', word: 'Cupcake', image: '/cards/cupcake.svg' },
    { id: '9', word: 'Dog', image: '/cards/dog.svg' },
    { id: '10', word: 'Duck', image: '/cards/duck.svg' },
    { id: '11', word: 'Egg', image: '/cards/egg.svg' },
    { id: '12', word: 'Fish', image: '/cards/fish.svg' },
    { id: '13', word: 'Fox', image: '/cards/fox.svg' },
    { id: '14', word: 'Frog', image: '/cards/frog.svg' },
    { id: '15', word: 'Hand', image: '/cards/hand.svg' },
    { id: '16', word: 'Horse', image: '/cards/horse.svg' },
    { id: '17', word: 'Ice', image: '/cards/ice.svg' },
    { id: '18', word: 'IceCream', image: '/cards/icecream.svg' },
    { id: '19', word: 'Key', image: '/cards/key.svg' },
    { id: '20', word: 'Leg', image: '/cards/leg.svg' },
    { id: '21', word: 'Lion', image: '/cards/lion.svg' },
    { id: '22', word: 'Mouse', image: '/cards/mouse.svg' },
    { id: '23', word: 'Mushroom', image: '/cards/mushroom.svg' },
    { id: '24', word: 'Pear', image: '/cards/pear.svg' },
    { id: '25', word: 'Pig', image: '/cards/pig.svg' },
    { id: '26', word: 'Rabbit', image: '/cards/rabbit.svg' },
    { id: '27', word: 'Shar', image: '/cards/shar.svg' },
    { id: '28', word: 'Snake', image: '/cards/snake.svg' },
    { id: '29', word: 'Tiger', image: '/cards/tiger.svg' },
    { id: '30', word: 'Train', image: '/cards/train.svg' },
    { id: '31', word: 'Umbrella', image: '/cards/umbrella.svg' },
    { id: '32', word: 'Wolf', image: '/cards/wolf.svg' },
];
